// <auto-generated />
namespace IdeasAPI.DataContexts.IdeasMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Entry_title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entry_title));
        
        string IMigrationMetadata.Id
        {
            get { return "201504101641207_Entry_title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
